# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-hello-world',
                'doc_host': 'https://chandan21gupta.github.io',
                'git_url': 'https://github.com/chandan21gupta/nbdev-hello-world',
                'lib_path': 'nbdev_hello_world'},
  'syms': {'nbdev_hello_world.core': {'nbdev_hello_world.core.foo': ('core.html#foo', 'nbdev_hello_world/core.py')}}}
